# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-macteefey-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Bachelors Projects', url: 'bachelors-projects.html'}
- {name: 'Masters Projects', url: 'masters-projects.html'}
- {name: 'Articles', url: 'articles.html'}
- {name: 'Bachelors Research', url: 'undergraduate.html'}
- {name: 'Masters Research', url: 'masters.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/macteefey'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/maclay-teefey/'}
- {icon: 'envelope',   link: 'mailto:macteefey@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
